source "https://rubygems.org"
gem 'google/apis/gmail_v1'
gem 'googleauth'
gem 'googleauth/stores/file_token_store'
gem 'fileutils'
gem 'gmail'
gem 'mail'
gem "google"
gem "twitter"
gem "pry"
gem "json"
gem "csv"
